### PR TITLE
Minor suggestions

### PR DESCRIPTION
**Pull request by boxed**
The flask example I fiddled with the diff into pseudo code.. you need to fix it to be correct and update the referenced example too...

### CODE REVIEW

**Comment by boxed** [comment]
For the workbook: 

- distrubiable -> distributable
- "mutmut found that I have at least 10 uncovered lines:" well, 10 surviving mutants
- "29/29  🎉 19  ⏰ 0  🤔 2  🙁 8%" <- remove the % !
- "What this mutations are telling us?" -> What are these mutants telling us?
- "We do not test that version is correct" -> We do not test that the version is correct
- "But, for some apps it is absolutelly required test.." -> But for some apps it is absolutely required to test..
- "we mutate a string, that is never checked" the comma is not needed, remove it
- "literaly" -> literally

**Comment by sobolevn** [comment]
Awesome. Thank you! 

Do you have other suggestions about good examples to show to QA people? 
I will fix the workbook and `flask` example shortly.

**Comment by boxed** [comment]
Not sure. There is a bit in tri.declarative for example, if you want some real world stuff. I just did a bunch of mutation testing yesterday that actually u covered a bug in the documentation generation code there. It's not super exciting, but it never seems to be :P

**Comment by sobolevn** [comment]
@boxed thanks, I will check it out.

**Pull request merged**
